version: '2'
services:
  userprofileservice:
    build:
      context: ./user-profile-service/src/main/docker/
      dockerfile: Dockerfile
    image: amdocsassignment/amdocs-userprofile-service:userprofileservice
    ports:
      - "8080:8080"
    environment:
        PROFILE: "default"
        SERVER_PORT: "8080"
        KAFKASERVER_URI: "kafkaserver"
        ZKSERVER_URI: "kafkaserver"
        KAFKASERVER_PORT:    "2181"
  kafkaserver:
    image: spotify/kafka
    ports:
      - 2181:2181
      - 9092:9092
  authorizationservice:
    build:
      context: ./authorization-service/src/main/docker/
      dockerfile: Dockerfile
    image: amdocsassignment/amdocs-authorization-service:authorizationservice
    ports:
      - "8085:8085"
    environment:
        PROFILE: "default"
        SERVER_PORT: "8085"
        KAFKASERVER_URI: "kafkaserver"
        ZKSERVER_URI: "kafkaserver"
        KAFKASERVER_PORT:    "2181"
   